sci3d = [
'''<?xml version="1.0" encoding="GB18030"?><SuperMapCache xmlns:sml="http://www.supermap.com/SuperMapCache/sci3d">''',
'''<sml:Version>1.000000</sml:Version>''',
'''<sml:NetCachePath/>''',
'''<sml:LocalCachePath/>''',
'''<sml:CacheName>[CacheName]</sml:CacheName>''',
'''<sml:StoreType>PureFiles</sml:StoreType>''',
'''<sml:Description/>''',
'''<sml:FileExtentName>[FileExtentName]</sml:FileExtentName>''',
'''<sml:Type>Image</sml:Type>''',
'''<sml:UpdateDataVersion>false</sml:UpdateDataVersion>''',
'''<sml:Width>[Width]</sml:Width>''',
'''<sml:Height>[Height]</sml:Height>''',
'''<sml:CellWidth>256</sml:CellWidth>''',
'''<sml:CellHeight>256</sml:CellHeight>''',
'''<sml:Bounds>''',
'''<sml:Left>[Left]</sml:Left>''',
'''<sml:Top>[Top]</sml:Top>''',
'''<sml:Right>[Right]</sml:Right>''',
'''<sml:Bottom>[Bottom]</sml:Bottom>''',
'''</sml:Bounds>''',
'''<sml:Level0>''',
'''<sml:Level0Width>180.000000</sml:Level0Width>''',
'''<sml:Level0Height>180.000000</sml:Level0Height>''',
'''</sml:Level0>''',
'''<sml:Levels>''',
'''<sml:Level>[Level]</sml:Level>''',
'''</sml:Levels>''',
'''</SuperMapCache>''',
]

webmkt_prj = [
'''<sml:CoordinateReferenceSystem>''',
'''<sml:Nameset>''',
'''<sml:name>User Define</sml:name>''',
'''</sml:Nameset>''',
'''<sml:Type>-1</sml:Type>''',
'''<sml:Units>METER</sml:Units>''',
'''<sml:GeographicCoordinateSystem>''',
'''<sml:Nameset>''',
'''<sml:Name>User Define</sml:Name>''',
'''</sml:Nameset>''',
'''<sml:Type>-1</sml:Type>''',
'''<sml:Units>DEGREE</sml:Units>''',
'''<sml:HorizonalGeodeticDatum>''',
'''<sml:Nameset>''',
'''<sml:Name>User Define</sml:Name>''',
'''</sml:Nameset>''',
'''<sml:Type>-1</sml:Type>''',
'''<sml:Ellipsoid>''',
'''<sml:Nameset>''',
'''<sml:Name>User Define</sml:Name>''',
'''</sml:Nameset>''',
'''<sml:Type>-1</sml:Type>''',
'''<sml:SemiMajorAxis>6378137.0000000000</sml:SemiMajorAxis>''',
'''<sml:InverseFlattening>0</sml:InverseFlattening>''',
'''</sml:Ellipsoid>''',
'''</sml:HorizonalGeodeticDatum>''',
'''<sml:PrimeMeridian>''',
'''<sml:Nameset>''',
'''<sml:Name>Greenwich</sml:Name>''',
'''</sml:Nameset>''',
'''<sml:Type>8901</sml:Type>''',
'''<sml:PrimeMeridian>0.0000000000</sml:PrimeMeridian>''',
'''</sml:PrimeMeridian>''',
'''</sml:GeographicCoordinateSystem>''',
'''<sml:MapProjection>''',
'''<sml:Nameset>''',
'''<sml:Name>Mercator</sml:Name>''',
'''</sml:Nameset>''',
'''<sml:Type>43004</sml:Type>''',
'''</sml:MapProjection>''',
'''<sml:Parameters>''',
'''<sml:FalseEasting>0.0000000000</sml:FalseEasting>''',
'''<sml:FalseNorthing>0.0000000000</sml:FalseNorthing>''',
'''<sml:CentralMeridian>0.0000000000</sml:CentralMeridian>''',
'''<sml:StandardParallel1>0.0000000000</sml:StandardParallel1>''',
'''<sml:StandardParallel2>0.0000000000</sml:StandardParallel2>''',
'''<sml:ScaleFactor>1.0000000000</sml:ScaleFactor>''',
'''<sml:CentralParallel>0.0000000000</sml:CentralParallel>''',
'''<sml:Azimuth>0.0000000000</sml:Azimuth>''',
'''<sml:FirstPointLongitude>0.0000000000</sml:FirstPointLongitude>''',
'''<sml:SecondPointLongitude>0.0000000000</sml:SecondPointLongitude>''',
'''</sml:Parameters>''',
'''</sml:CoordinateReferenceSystem>''',
]

sci30 = [
'''<?xml version="1.0" encoding="GB2312"?><SuperMapCache xmlns:sml="http://www.supermap.com/sml">''',
'''<sml:NetCachePath/>''',
'''<sml:LocalCachePath/>''',
'''<sml:CacheName>[value]</sml:CacheName>''',
'''<sml:ImageFormat>[value]</sml:ImageFormat>''',
'''<sml:ImageWidth>[value]</sml:ImageWidth>''',
'''<sml:ImageHeight>[value]</sml:ImageHeight>''',
'''<sml:ImageCellWidth>256</sml:ImageCellWidth>''',
'''<sml:ImageCellHeight>256</sml:ImageCellHeight>''',
'''<sml:ImageCompress>75</sml:ImageCompress>''',
'''<sml:IsTransparent>FALSE</sml:IsTransparent>''',
'''<sml:ImageLogicalWidth>677</sml:ImageLogicalWidth>''',
'''<sml:ImageLogicalHeight>677</sml:ImageLogicalHeight>''',
'''<sml:BaseScale>[value]</sml:BaseScale>''',
'''<sml:BaseWidth>512</sml:BaseWidth>''',
'''<sml:BaseHeight>512</sml:BaseHeight>''',
'''<sml:BaseLogicalWidth>1355</sml:BaseLogicalWidth>''',
'''<sml:BaseLogicalHeight>1355</sml:BaseLogicalHeight>''',
'''<sml:ImageBounds>''',
'''<sml:ImageLeft>[value]</sml:ImageLeft>''',
'''<sml:ImageTop>[value]</sml:ImageTop>''',
'''<sml:ImageRight>[value]</sml:ImageRight>''',
'''<sml:ImageBottom>[value]</sml:ImageBottom>''',
'''</sml:ImageBounds>''',
'''<sml:StoreType>PureFiles</sml:StoreType>''',
'''<sml:MapName>[value]</sml:MapName>''',
'''<sml:MapBounds>''',
'''<sml:MapLeft>[value]</sml:MapLeft>''',
'''<sml:MapTop>[value]</sml:MapTop>''',
'''<sml:MapRight>[value]</sml:MapRight>''',
'''<sml:MapBottom>[value]</sml:MapBottom>''',
'''</sml:MapBounds>''',
'''<MapCache>''',
'''</MapCache>''',
'''<sml:PixelFormat>32</sml:PixelFormat>''',
'''<sml:UseOutPutRegion>FALSE</sml:UseOutPutRegion>''',
'''<sml:MapCacheStrategy>2</sml:MapCacheStrategy>''',
'''</SuperMapCache>''',
	]

sci31 = [
'''<?xml version="1.0" encoding="GB2312"?><SuperMapCache xmlns:sml="http://www.supermap.com/sml">''',
'''<sml:NetCachePath/>''',
'''<sml:LocalCachePath/>''',
'''<sml:CacheName>[value]</sml:CacheName>''',
'''<sml:ImageFormat>[value]</sml:ImageFormat>''',
'''<sml:ImageWidth>[value]</sml:ImageWidth>''',
'''<sml:ImageHeight>[value]</sml:ImageHeight>''',
'''<sml:ImageCellWidth>256</sml:ImageCellWidth>''',
'''<sml:ImageCellHeight>256</sml:ImageCellHeight>''',
'''<sml:ImageCompress>75</sml:ImageCompress>''',
'''<sml:IsTransparent>FALSE</sml:IsTransparent>''',
'''<sml:ImageLogicalWidth>677</sml:ImageLogicalWidth>''',
'''<sml:ImageLogicalHeight>677</sml:ImageLogicalHeight>''',
'''<sml:BaseScale>[value]</sml:BaseScale>''',
'''<sml:BaseWidth>256</sml:BaseWidth>''',
'''<sml:BaseHeight>256</sml:BaseHeight>''',
'''<sml:BaseLogicalWidth>677</sml:BaseLogicalWidth>''',
'''<sml:BaseLogicalHeight>677</sml:BaseLogicalHeight>''',
'''<sml:ImageBounds>''',
'''<sml:ImageLeft>[value]</sml:ImageLeft>''',
'''<sml:ImageTop>[value]</sml:ImageTop>''',
'''<sml:ImageRight>[value]</sml:ImageRight>''',
'''<sml:ImageBottom>[value]</sml:ImageBottom>''',
'''</sml:ImageBounds>''',
'''<sml:StoreType>PureFiles</sml:StoreType>''',
'''<sml:MapName>[value]</sml:MapName>''',
'''<sml:MapBounds>''',
'''<sml:MapLeft>[value]</sml:MapLeft>''',
'''<sml:MapTop>[value]</sml:MapTop>''',
'''<sml:MapRight>[value]</sml:MapRight>''',
'''<sml:MapBottom>[value]</sml:MapBottom>''',
'''</sml:MapBounds>''',
'''<MapCache>''',
'''</MapCache>''',
'''<sml:PixelFormat>32</sml:PixelFormat>''',
'''<sml:UseOutPutRegion>FALSE</sml:UseOutPutRegion>''',
'''<sml:MapCacheStrategy>2</sml:MapCacheStrategy>''',
'''</SuperMapCache>''',
	]
sci31_scale = [
'''<MapCacheState>''',
'''<sml:Scale>[value]</sml:Scale>''',
'''<sml:ScaleFolder>[value]</sml:ScaleFolder>''',
'''<sml:ImageCount>0</sml:ImageCount>''',
'''<sml:ExistImageCount>0</sml:ExistImageCount>''',
'''<sml:HashCode/>''',
'''<sml:StartTime>1899-12-30 00:00:00</sml:StartTime>''',
'''<sml:EndTime>1899-12-30 00:00:00</sml:EndTime>''',
'''</MapCacheState>''',
]

sci40 = [
'''<?xml version="1.0" encoding="GB2312"?><SuperMapCache xmlns:sml="http://www.supermap.com/sml">''',
'''<sml:NetCachePath/>''',
'''<sml:LocalCachePath/>''',
'''<sml:CacheName>[value]</sml:CacheName>''',
'''<sml:ImageFormat>[value]</sml:ImageFormat>''',
'''<sml:ImageWidth>[value]</sml:ImageWidth>''',
'''<sml:ImageHeight>[value]</sml:ImageHeight>''',
'''<sml:ImageCellWidth>256</sml:ImageCellWidth>''',
'''<sml:ImageCellHeight>256</sml:ImageCellHeight>''',
'''<sml:ImageCompress>75</sml:ImageCompress>''',
'''<sml:IsTransparent>FALSE</sml:IsTransparent>''',
'''<sml:ImageLogicalWidth>677</sml:ImageLogicalWidth>''',
'''<sml:ImageLogicalHeight>677</sml:ImageLogicalHeight>''',
'''<sml:BaseScale>[value]</sml:BaseScale>''',
'''<sml:BaseWidth>512</sml:BaseWidth>''',
'''<sml:BaseHeight>512</sml:BaseHeight>''',
'''<sml:BaseLogicalWidth>1355</sml:BaseLogicalWidth>''',
'''<sml:BaseLogicalHeight>1355</sml:BaseLogicalHeight>''',
'''<sml:ImageBounds>''',
'''<sml:ImageLeft>[value]</sml:ImageLeft>''',
'''<sml:ImageTop>[value]</sml:ImageTop>''',
'''<sml:ImageRight>[value]</sml:ImageRight>''',
'''<sml:ImageBottom>[value]</sml:ImageBottom>''',
'''</sml:ImageBounds>''',
'''<sml:StoreType>PureFiles</sml:StoreType>''',
'''<sml:MapName></sml:MapName>''',
'''<sml:MapBounds>''',
'''<sml:MapLeft>[value]</sml:MapLeft>''',
'''<sml:MapTop>[value]</sml:MapTop>''',
'''<sml:MapRight>[value]</sml:MapRight>''',
'''<sml:MapBottom>[value]</sml:MapBottom>''',
'''</sml:MapBounds>''',
'''<MapCache>''',
'''<MapCacheState>''',
'''</MapCacheState>''',
'''</MapCache>''',
'''<sml:PixelFormat>32</sml:PixelFormat>''',
'''<sml:UseOutPutRegion>FALSE</sml:UseOutPutRegion>''',
'''<sml:MapCacheStrategy>1</sml:MapCacheStrategy>''',
'''</SuperMapCache>''',
]

sci40_scale = [
'''<sml:Scale>[value]</sml:Scale>''',
'''<sml:ScaleFolder>[value]</sml:ScaleFolder>''',
'''<sml:ImageCount>0</sml:ImageCount>''',
'''<sml:ExistImageCount>0</sml:ExistImageCount>''',
'''<sml:HashCode>8B185AB8FIX</sml:HashCode>''',
'''<sml:StartTime>1899-12-30 00:00:00</sml:StartTime>''',
'''<sml:EndTime>1899-12-30 00:00:00</sml:EndTime>''',
]
